//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolcadorIkor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Port=3306;Database=dbIkor;Uid=root;Pwd=admin;")]
        public string InstanciaServerMysql {
            get {
                return ((string)(this["InstanciaServerMysql"]));
            }
            set {
                this["InstanciaServerMysql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string cModo {
            get {
                return ((string)(this["cModo"]));
            }
            set {
                this["cModo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("balzarowsky@gmail.com")]
        public string strCuentaReceptora {
            get {
                return ((string)(this["strCuentaReceptora"]));
            }
            set {
                this["strCuentaReceptora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daemonikor@gmail.com")]
        public string strCuentaEmisora {
            get {
                return ((string)(this["strCuentaEmisora"]));
            }
            set {
                this["strCuentaEmisora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V0lc4d0r2015")]
        public string strContrasenaEmisora {
            get {
                return ((string)(this["strContrasenaEmisora"]));
            }
            set {
                this["strContrasenaEmisora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string strRepoXMLs {
            get {
                return ((string)(this["strRepoXMLs"]));
            }
            set {
                this["strRepoXMLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string strRepoDATs {
            get {
                return ((string)(this["strRepoDATs"]));
            }
            set {
                this["strRepoDATs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public string strMiliTimerConn {
            get {
                return ((string)(this["strMiliTimerConn"]));
            }
            set {
                this["strMiliTimerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string cModoD {
            get {
                return ((string)(this["cModoD"]));
            }
            set {
                this["cModoD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string strRepoTXTs {
            get {
                return ((string)(this["strRepoTXTs"]));
            }
            set {
                this["strRepoTXTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Port=3306;Database=dbIkor;Uid=root;Pwd=admin;")]
        public string InstanciaServer {
            get {
                return ((string)(this["InstanciaServer"]));
            }
            set {
                this["InstanciaServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.48.182\\SQLEXPRESS;initial catalog=dbIkorPCB;user id=UserIkor;" +
            "password=admin;Connection Timeout=180000")]
        public string InstanciaServerSql {
            get {
                return ((string)(this["InstanciaServerSql"]));
            }
            set {
                this["InstanciaServerSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public string strMiliTimerConnSQL {
            get {
                return ((string)(this["strMiliTimerConnSQL"]));
            }
            set {
                this["strMiliTimerConnSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string strRespaldoSQL {
            get {
                return ((string)(this["strRespaldoSQL"]));
            }
            set {
                this["strRespaldoSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string bAplicaResp {
            get {
                return ((string)(this["bAplicaResp"]));
            }
            set {
                this["bAplicaResp"] = value;
            }
        }
    }
}
